version: '3.8'

services:
    mariadb:
        image: mariadb:lts
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=root
        volumes:
            - mariadb-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3306
        ports:
            - 8080:80
        volumes:
            - './themes/blueberry:/var/www/html/themes/blueberry'
            - './themes/boodark:/var/www/html/themes/boodark'
            - './themes/boodark-nord:/var/www/html/themes/boodark-nord'
volumes:
    mariadb-data:
        driver: local